### ISSUE TITLE
Modify the response structure in APIs

### ISSUE THREAD

**Issue by ankurnarkhede** [Real-Dev-Squad/calendar-API#39]
Modify the APIs response structure in the following manner:
```json
{
    "message": "",
    "data": {// actual response object},
    "error": {// error, if any}
}
```

Create a generic response struct and use it in every API response.

**Comment by ankurnarkhede** [comment]
Modify the APIs response structure in the following manner:
```json
{
    "message": "",
    "data": {// actual response object},
    "error": {// error, if any}
}
```

Create a generic response struct and use it in every API response.

**Comment by ankurnarkhede** [comment]
@prakashchoudhary07 , can you take this up?

**Comment by harshith-venkatesh** [comment]
As per the discussion in the call and suggestion by @prakashchoudhary07 , @shubham-y would be taking up the task.

**Comment by ankurnarkhede** [comment]
@shubham-y , any update here?

**Comment by harshith-venkatesh** [comment]
@shubham-y , please let us know in case you got blocked somewhere

**Comment by ankurnarkhede** [comment]
@shubham-y : https://github.com/Real-Dev-Squad/calendar-API/pull/45#issuecomment-1352500278
